//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        public int C_ID { get; set; }
        [Required(ErrorMessage ="Name is required")]
        [StringLength(50,MinimumLength =3,ErrorMessage ="Name must be 3-50 characters")]
        [RegularExpression(@"^[A-Za-z\s]+$",ErrorMessage ="Name should contain only letters")]
        public string C_NAME { get; set; }
        public Nullable<System.DateTime> C_DOB { get; set; }
        public string C_PAN { get; set; }
        [RegularExpression(@"^[6-9]\d{9}$",ErrorMessage ="Enter valid 10 digit mobile number")]
        public string C_MOBILE { get; set; }
        [EmailAddress(ErrorMessage ="Enter valid email address")]
        public string C_EMAIL { get; set; }
        public Nullable<decimal> C_SALARY { get; set; }
        public string C_ADDRESS { get; set; }
        public string C_GENDER { get; set; }
        public string C_PASSWORD { get; set; }
    }
}
