//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;

    public partial class Employee
    {
        [Key]
        
        public int E_ID { get; set; }
        public string Employee_Name { get; set; }
        public Nullable<int> E_Department_ID { get; set; }
        public string E_Mobile { get; set; }
        public string E_Email { get; set; }
        public Nullable<System.DateTime> E_DOB { get; set; }
        public string E_Gender { get; set; }
        public string E_Address { get; set; }
        public string E_PAN { get; set; }
        public string E_PASSWORD { get; set; }
    }
  
    
}
