//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Fixed_Deposit_Account
    {

        public string FD_ACCOUNT_ID { get; set; }
        [ForeignKey("C_ID")]
        public Nullable<int> FD_CUSTOMER_ID { get; set; }
        public Nullable<System.DateTime> FD_START_DATE { get; set; }
        public Nullable<System.DateTime> FD_END_DATE { get; set; }
        [Range(1, 20, ErrorMessage = "ROI must be between 1% and 20%")]
        public Nullable<decimal> FD_ROI { get; set; }
        [Range(1, 30, ErrorMessage = "Tenure must be between 1 and 30 years")]
        public Nullable<int> FD_TENURE { get; set; }
        [Range(1000,10000000,ErrorMessage ="Loan amount must be in the range of 1000-10000000")]
        public Nullable<decimal> FD_AMOUNT { get; set; }
    }
}
