//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixed_Deposit_Transaction
    {
        public string FT_TRANSACTION_ID { get; set; }
        public Nullable<System.DateTime> FT_TRANSACTION_DATE { get; set; }
        public Nullable<int> FT_ACCOUNT_ID { get; set; }
        public Nullable<decimal> FT_AMOUNT { get; set; }
        public Nullable<decimal> FT_PRECLOSURE { get; set; }
    }
}
