//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan_Transaction
    {
        public string LT_TRANSACTION_ID { get; set; }
        public Nullable<System.DateTime> LT_TRANSACTION_DATE { get; set; }
        public Nullable<int> LT_ACCOUNT_ID { get; set; }
        public Nullable<decimal> LT_AMOUNT { get; set; }
        public Nullable<System.DateTime> LT_START_DATE { get; set; }
        public Nullable<int> LT_TENURE { get; set; }
        public Nullable<decimal> LT_EMI { get; set; }
        public Nullable<System.DateTime> LT_EMI_DATE { get; set; }
        public Nullable<decimal> LT_PRECLOSE { get; set; }
    }
}
