//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public string M_ID { get; set; }
        public string M_NAME { get; set; }
        public string M_MOBILE { get; set; }
        public string M_EMAIL { get; set; }
        public string M_ADDRESS { get; set; }
        public Nullable<System.DateTime> M_DOB { get; set; }
        public string M_PAN { get; set; }
        public string M_GENDER { get; set; }
        public string M_PASSWORD { get; set; }
    }
}
