//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankDbEntities : DbContext
    {
        public BankDbEntities()
            : base("name=BankDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Fixed_Deposit_Account> Fixed_Deposit_Account { get; set; }
        public virtual DbSet<Fixed_Deposit_Transaction> Fixed_Deposit_Transaction { get; set; }
        public virtual DbSet<Home_Loan_Account> Home_Loan_Account { get; set; }
        public virtual DbSet<Loan_Transaction> Loan_Transaction { get; set; }
        public virtual DbSet<LoginPage> LoginPages { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Savings_Account> Savings_Account { get; set; }
        public virtual DbSet<Savings_Transaction> Savings_Transaction { get; set; }
        
    }
}
