//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Savings_Transaction
    {
        public string ST_TRANSACTION_ID { get; set; }
        public Nullable<System.DateTime> ST_TRANSACTION_DATE { get; set; }
        public Nullable<int> ST_ACCOUNT_ID { get; set; }
        public Nullable<decimal> ST_AMOUNT { get; set; }
        public Nullable<decimal> ST_DEPOSIT { get; set; }
        public Nullable<decimal> ST_WITHDRAWL { get; set; }
    }
}
